### ISSUE TITLE
Case-sensitive strings are an affront to everything we hold dear

### ISSUE THREAD

**Issue by thieman** [pizzafox/exa-syntax-highlighting#6]
As we all know, string manipulation is hard. Luckily for all of us, the Execution Agent Engineering Task Force (EXAETF) saved us from a lot of the trouble of strings by mandating back in the 80s that all strings be ASCII encoded and strictly case-insensitive. That's why all the most advanced computer systems of today, from highway signs to bank accounts to MMORPG backends, work exclusively in case-insensitive ASCII strings.

This is why I was surprised to find that this (very neat) syntax highlighter program had somehow decided that case sensitivity was a thing again! Imagine my surprise when I typed a benign `copy` command only to realize that it was not highlighted. However, `COPY` seems to get highlighted just fine. I knew something was afoot when I saw this.

Of course, any conformant EDE (EXA Development Environment) will convert input text into a standard case-insensitive format (generally upper-case) upon entry. It should therefore be harmless to support case variants within this extension. Please consider following universally-adhered-to EXAETF standards regarding strings within your "visual" coding extension. 

Happy hacking and thanks for the extension.

**Comment by pizzafox** [comment]
`v1.3.0` should allow lowercase instructions, but some might be accidentally displayed as invalid. If you see any weird behavior please open another issue!

**Comment by thieman** [comment]
Looks fixed on my end, thanks! Please note the image in your README is now out of date and still showing lowercase instructions not highlighting. Doesn't seem super urgent to fix but might generate some false bug reports.

**Comment by pizzafox** [comment]
🤦 I'll get that updated, good catch.
